from __future__ import annotations

from datetime import datetime, timezone
import json
import re
from typing import Any
from uuid import UUID

from jinja2 import BaseLoader, Environment
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions import ConflictError
from app.services.snapshot_service import SnapshotService, build_event_property_map

TYPESCRIPT_TEMPLATE = """// Generated by Trackboard. Do not edit by hand.
// Published version: {{ version_number }}
// Generated: {{ generated_at }}

{% for event in events %}
export interface {{ event.event_name | interface_name }}Properties {
{% for prop in event.properties %}
  {{ prop.name | ts_property_key }}{{ "" if prop.required else "?" }}: {{ prop.type | ts_type(prop.constraints) }};
{% endfor %}
}

{% endfor %}
export type TrackingEvent =
{% for event in events %}
  | { event: {{ event.event_name | ts_string }}; properties: {{ event.event_name | interface_name }}Properties }
{% endfor %};
"""

TS_IDENTIFIER_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _interface_name(event_name: str) -> str:
    chunks = [chunk for chunk in re.split(r"[^0-9A-Za-z]+", event_name) if chunk]
    name = "".join(chunk[:1].upper() + chunk[1:] for chunk in chunks)
    if not name or name[0].isdigit():
        return f"Event{name or 'Schema'}"
    return name


def _ts_type(prop_type: str, constraints: dict[str, Any]) -> str:
    enum_values = constraints.get("enum_values") if constraints else None
    if enum_values:
        return " | ".join(_ts_string(str(value)) for value in enum_values)
    return {
        "string": "string",
        "integer": "number",
        "float": "number",
        "boolean": "boolean",
        "array": "unknown[]",
        "object": "Record<string, unknown>",
    }.get(prop_type, "unknown")


def _ts_property_key(name: str) -> str:
    if TS_IDENTIFIER_RE.match(name):
        return name
    return _ts_string(name)


def _ts_string(value: str) -> str:
    return json.dumps(value)


class CodegenService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.snapshot_service = SnapshotService(db)
        self.environment = Environment(loader=BaseLoader(), autoescape=False)  # nosec B701
        self.environment.filters["interface_name"] = _interface_name
        self.environment.filters["ts_property_key"] = _ts_property_key
        self.environment.filters["ts_string"] = _ts_string
        self.environment.filters["ts_type"] = lambda prop_type, constraints: _ts_type(
            prop_type, constraints
        )

    async def generate_typescript(self, plan_id: UUID) -> str:
        version = await self.snapshot_service.get_latest_version(plan_id)
        if version is None:
            raise ConflictError(
                "Generate code requires a published version.",
                code="no_published_version",
            )

        template = self.environment.from_string(TYPESCRIPT_TEMPLATE)
        return template.render(
            version_number=version.version_number,
            events=self._event_entries(version.snapshot),
            generated_at=self._now(),
        )

    async def generate_json_schema(self, plan_id: UUID) -> dict[str, Any]:
        version = await self.snapshot_service.get_latest_version(plan_id)
        if version is None:
            raise ConflictError(
                "Generate code requires a published version.",
                code="no_published_version",
            )

        event_schemas = []
        for event in version.snapshot.get("events", []):
            property_map = build_event_property_map(version.snapshot, event)
            properties: dict[str, Any] = {}
            required: list[str] = []
            for property_name, schema in property_map.items():
                properties[property_name] = {
                    "type": _json_schema_type(schema["type"]),
                    "description": schema.get("description"),
                }
                enum_values = (schema.get("constraints") or {}).get("enum_values")
                if enum_values:
                    properties[property_name]["enum"] = enum_values
                if schema.get("required"):
                    required.append(property_name)

            event_schemas.append(
                {
                    "type": "object",
                    "properties": {
                        "event": {"const": event["event_name"]},
                        "properties": {
                            "type": "object",
                            "properties": properties,
                            "required": sorted(required),
                            "additionalProperties": False,
                        },
                    },
                    "required": ["event", "properties"],
                }
            )

        return {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "title": version.snapshot.get("name", "Trackboard Plan"),
            "oneOf": event_schemas,
        }

    async def generate_python(self, plan_id: UUID) -> str:
        return await self.generate_typescript(plan_id)

    async def generate_dbt_tests(self, plan_id: UUID) -> str:
        return await self.generate_typescript(plan_id)

    async def generate_snowflake(self, plan_id: UUID) -> str:
        return await self.generate_typescript(plan_id)

    async def generate_bigquery(self, plan_id: UUID) -> str:
        return await self.generate_typescript(plan_id)

    async def generate_clickhouse(self, plan_id: UUID) -> str:
        return await self.generate_typescript(plan_id)

    def _event_entries(self, snapshot: dict[str, Any]) -> list[dict[str, Any]]:
        events = []
        for event in snapshot.get("events", []):
            property_map = build_event_property_map(snapshot, event)
            events.append(
                {
                    "event_name": event["event_name"],
                    "properties": [property_map[name] for name in sorted(property_map)],
                }
            )
        return events

    @staticmethod
    def _now() -> str:
        return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _json_schema_type(prop_type: str) -> str:
    return {
        "string": "string",
        "integer": "integer",
        "float": "number",
        "boolean": "boolean",
        "array": "array",
        "object": "object",
    }.get(prop_type, "string")
