import type { ContractProperty, TrackboardContract } from "./contract.js";
import { normalizeContract, propertyMap } from "./contract.js";

export function generateTypescript(contractInput: TrackboardContract): string {
  const contract = normalizeContract(contractInput);
  const chunks = [
    "// Generated by Trackboard. Do not edit by hand.",
    `// Published version: ${contract.version_number ?? "unknown"}`,
    "",
  ];
  for (const event of contract.events) {
    const interfaceName = `${toPascalCase(event.event_name)}Properties`;
    chunks.push(`export interface ${interfaceName} {`);
    for (const prop of propertyMap(contract, event).values()) {
      chunks.push(`  ${propertyKey(prop.name)}${prop.required ? "" : "?"}: ${tsType(prop)};`);
    }
    chunks.push("}", "");
  }
  chunks.push("export type TrackingEvent =");
  for (const event of contract.events) {
    chunks.push(`  | { event: ${JSON.stringify(event.event_name)}; properties: ${toPascalCase(event.event_name)}Properties }`);
  }
  chunks.push(";", "");
  chunks.push("export interface TrackboardClient {");
  chunks.push("  track(input: TrackingEvent): Promise<void>;");
  chunks.push("}", "");
  for (const event of contract.events) {
    const name = toPascalCase(event.event_name);
    chunks.push(`export function track${name}(`);
    chunks.push("  client: TrackboardClient,");
    chunks.push(`  properties: ${name}Properties,`);
    chunks.push("): Promise<void> {");
    chunks.push(`  return client.track({ event: ${JSON.stringify(event.event_name)}, properties });`);
    chunks.push("}", "");
  }
  return `${chunks.join("\n")}\n`;
}

function tsType(prop: ContractProperty): string {
  const enumValues = prop.constraints?.enum_values;
  if (Array.isArray(enumValues) && enumValues.length > 0) {
    return enumValues.map((value) => JSON.stringify(String(value))).join(" | ");
  }
  if (prop.type === "string") return "string";
  if (prop.type === "integer" || prop.type === "float") return "number";
  if (prop.type === "boolean") return "boolean";
  if (prop.type === "array") return "unknown[]";
  if (prop.type === "object") return "Record<string, unknown>";
  return "unknown";
}

function propertyKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function toPascalCase(value: string): string {
  const name = value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
  return /^[0-9]/.test(name) ? `Event${name}` : name || "EventSchema";
}
